//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkDbDemo.Web.DataModels.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string GUID { get; set; }
        public string Name { get; set; }
        public string DepartmentCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
